### ISSUE TITLE
Props not updating

### ISSUE THREAD

**Issue by mirago** [binbytes/react-native-simple-modal-picker#1]
Hello, I have used this picker in my project, works well. 

However I noticed that the data prop is not updating. I have a few fields that depend on other fields, and noticed that the options are not changing. 

I've added this code 

```
   componentWillReceiveProps( nextProps ) {
        this.setState({
            dataSource: this.state.dataSource.cloneWithRows( nextProps.data )
        });
    }
```

This fixes the issue, but I was wondering whether it is a good fix?

**Comment by bhavik66** [comment]
Hi @mirago,

Thanks for the suggestion. Your code is perfect and I added it.
