### ISSUE TITLE
This lib doesn't work on RN 0.60.4

### ISSUE THREAD

**Issue by fauker** [binbytes/react-native-simple-modal-picker#2]
Sup! 

I'm trying to use this lib, but it doesn't work in RN 0.60.4. 

ListView is [deprecated](https://facebook.github.io/react-native/docs/listview).

![image](https://user-images.githubusercontent.com/7989766/62590769-d8eb7380-b8a3-11e9-8f7f-cf083f1367a1.png)

Could we replace ListView with FlatList?

**Comment by BransonGitomeh** [comment]
#3 should fix it
